baseurl = "https://blog.pandared.net"
title = "Panda R E D Blog"
author = "Panda"
paginate = 3
theme = "arabica"

[params]
    description = "simple"
    dateFormatToUse = "2006-01-02"
    replaceGoogleFonts = "fonts.loli.net"
#    twitter = "example"
#    facebook = "example"
